package com.example.shows_lovre_nincevic_pestilence01.utils

object Constants {

    const val SHOW_EXTRA_KEY: String = "show_extra_key"
    const val REMEMBER_ME_KEY: String = "remember_me_key"
    const val USERNAME_KEY: String = "username_key"
    const val EMAIL_KEY: String = "email_key"
    const val AWS_URL: String = "https://localhost:3000"
    const val REGISTERED_KEY: String = "registered_key"
    const val SHARED_PREFERENCES: String = "SharedPrefs"
    const val DEFAULT_USERNAME: String = "John Doe"
    const val DEFAULT_EMAIL: String = "JohnDoe@gmail.com"
    const val LOG_OUT_PROMPT: String = "Are you sure you wish to log out?"
    const val YES: String = "Yes"
    const val NO: String = "No"
    const val LOG_OUT_SUCCESSFUL: String = "You have successfully logged out!"
    const val ENABLE_PERMISSIONS: String = "Please enable permissions for this feature"
    const val IMAGE_SOURCE: String = "Where do you want to take your picture from?"
    const val CAMERA: String = "CAMERA"
    const val STORAGE: String = "STORAGE"
    const val FEEDBACK: String = "Thanks for your feedback!"
    const val SOMETHING_WRONG: String = "Oops! Something went wrong!"
    const val REVIEW_PROBLEM: String = "There was a problem posting your review."
    const val CHECK_CONNECTION: String = "Please check your internet connection"
    const val EMAIL_TAKEN: String = "Email address already taken. Please choose another one!"
    const val VALID_EMAIL: String = "Please provide a valid email address"
    const val PASSWORDS_DO_NOT_MATCH: String = "Passwords do not match"
    const val REGISTRATION_SUCCESSFUL: String = "You have successfully registered!"
    const val VALID_CREDENTIALS: String = "Please provide valid credentials!"
    const val REGISTRATION_SUCCESSFUL_NEWLINE: String = "Registration \nSuccessful!"
    const val LOGIN: String = "Login"
    const val SUCCESSFUL_LOGIN: String = "You have successfully logged in!"
    const val SIGN_BEFORE_CONTINUING: String = "You need to sign in or sign up before continuing"
    const val SHOW: String = "show"
    const val REVIEW: String = "review"
    const val CANNOT_FIND_SHOW: String = "We couldn't find this show! Check ID"
    const val PROVIDE_INTERNET: String = "Please provide internet connection for this feature"

}